TOKEN = "*****"

SERVER = "--"
DATABASE = "--"
USER = "--"
PASSWORD = "--"
DRIVER = "SQL Server Native Client 11.0"
CONNECTION_STRING = f"DRIVER={{{DRIVER}}};UID={USER};PWD={PASSWORD};WSID=SVETOFORBOT;SERVER={SERVER};DATABASE={DATABASE}"
